### ISSUE TITLE
Support for serial port

### ISSUE THREAD

**Issue by haakoo** [dsuarezv/mavlink.net#1]
From what I can understand from looking at this library and [mavlinkclient-cs](https://github.com/dsuarezv/mavlinkclient-cs), mavlink.net only implements a UDP-transport layer. Do you see a need for a serial port implementation too, or do you recommend to use a _serial to ethernet converter_?

**Comment by amin347** [comment]
could you please give me an example of 'Arm/Disarm' with mavlink.Net. We use pixhawk and telemetry.
i Can't generate Message and send it.

**Comment by dsuarezv** [comment]
Hava a look at https://github.com/dsuarezv/mavlinkclient-cs. Maybe it helps.
