### ISSUE TITLE
Udp message sending

### ISSUE THREAD

**Issue by vitiokss** [dsuarezv/mavlink.net#10]
Hi David,
First of all Thank you very much for the effort and great implementation. I have tried to find your personal contact information, but can't succeed so i just writing here.

I do have question what am i doing wrong in this case? Let's say i want to change the mode of the UAV, so i am sending the message like that. It just a small snippet from your mavlinknet-cli, where most of the examples were just getting the heartbeat data.

           mMavlinkClient = new MavLinkUdpTransport()
            {
                TargetIpAddress = targetIp,
                UdpTargetPort = targetPort, 
                UdpListeningPort = listenPort
            };

            mMavlinkClient.OnPacketReceived += mMavlinkClient_OnPacketReceived;
            mMavlinkClient.Initialize();
          UasCommandInt command = new UasCommandInt()
          {
            Command = MavCmd.DoSetMode,
            Param1 = (float)MavMode.AutoDisarmed,
            TargetComponent = mMavlinkClient.MavlinkComponentId,
            TargetSystem = mMavlinkClient.MavlinkSystemId
          };
          mMavlinkClient.SendMessage(command);

But it seems that my UAV does not take any action. Do i missing something? Can you please help a bit to understand correctly.

Moreover lets say i request for paramlist from UAV. So to get it, should i just catch all of them in the event handler mMavlinkClient_OnPacketReceived ?

Thank you very much for your answer, it would help me a lot to understand it.

**Comment by dsuarezv** [comment]
Hi, 

SendMessage is enough to actually send the message to the UAV, so my guess is that your problem may be that you need to do more things (send more messages) to change the state. 

I would recommend using the mavlinkscope sample project [here](https://github.com/dsuarezv/mavlinkclient-cs/tree/master/mavlinkscope) to "sniff" the traffic between  the ground station and the UAV to see what messages are needed to perform the action you want. 

about OnPacketReceived, yes, all packets are sent to that event, so you can process them there. 

Cheers!

**Comment by BTBlueSkies** [comment]
Are you able to get the heartbeat  message?
