### ISSUE TITLE
Once the new GeneratedMessages.cs is generated, the build fails because 256 is assigned to a byte variable

### ISSUE THREAD

**Issue by BrianCohen** [dsuarezv/mavlink.net#15]
No need to explain further...

**Comment by dsuarezv** [comment]
Maybe you need to explain what messages.xml file you are using and what field is raising the error?

Maybe, only maybe...

**Comment by dsuarezv** [comment]
I have open an issue in the mavlink project regarding this, let's see what happens. 

https://github.com/mavlink/mavlink/issues/570

**Comment by BrianCohen** [comment]
Sorry, I was using the common.xml 
Thanks
