### ISSUE TITLE
Example project request

### ISSUE THREAD

**Issue by jonathancurrie** [dsuarezv/mavlink.net#17]
Hi,

Great project - mavlinkgen works perfectly, thanks for making it available. However getting started with the mavlink.net project requires a bit of navigation through the source to work out what needs to be created, modified, etc. Any chance of a quick demo project to be added to the repo to make it easier for newbies (like me) to get started?

Thanks!
Jonathan

**Comment by amin347** [comment]
Hi jonathan i Wrote a Sample Code in Mavlink.net, it can get Data but it can't Send Them or not work on AutoPilot.
https://github.com/amin347/TestMavlink.net
i  you can any Result from This Come Back to me.
Thanks!

**Comment by jonathancurrie** [comment]
Hi, I've written my own interface now, just thought it would be a nice addition to the project!

**Comment by dsuarezv** [comment]
It'd be great, please post more details.

**Comment by jonathancurrie** [comment]
It's a bit of a mess at the moment, but I can tidy it up if you want? Wraps a background worker over the transport layer and adds a concurrent queue so GUI updates can be done via a progress changed event handler.

**Comment by dsuarezv** [comment]
Great! Post here.
