### ISSUE TITLE
Generating .NET output from multiple message definition .xml files

### ISSUE THREAD

**Issue by jonathancurrie** [dsuarezv/mavlink.net#18]
It seems if I call mavlinkgen with multiple definition files (e.g. `mavlinkgen common.xml mine.xml --output="test.cs"`) all I get is a test.cs with the message definition from the last definition file. Is there a way to merge all definitions into a single generated output?

**Comment by dsuarezv** [comment]
Specify only one file in the command line and use includes inside the file.

**Comment by jonathancurrie** [comment]
Many thanks for the quick response. I can't find the syntax how to include a message definition in e.g. common.xml - any suggestions?

**Comment by jonathancurrie** [comment]
Annoying, sorry, found it.

**Comment by jonathancurrie** [comment]
Working, thank you!

**Comment by dsuarezv** [comment]
I leave it here for reference: 
```
<?xml version='1.0'?>
<mavlink>
	<include>common.xml</include>
    ...
```
