### ISSUE TITLE
Missing enum for message IDs?

### ISSUE THREAD

**Issue by jonathancurrie** [dsuarezv/mavlink.net#19]
Is it possible to add an enum for the message IDs? Something like:

`public enum MavMsgIDs { 
    Heartbeat = 0;
    SysStatus = 1;
    SystemTime = 2;
     ..
}`

It would just make my method of decoding messages a little easier. I can't find this functionality so far.

**Comment by jonathancurrie** [comment]
I've added code to CSharpGenerator.cs that does this - useful addition?

**Comment by dsuarezv** [comment]
Yes, please PR.

**Comment by jonathancurrie** [comment]
Done.
