### ISSUE TITLE
Missing UasMessage Class

### ISSUE THREAD

**Issue by WillBaldwin** [dsuarezv/mavlink.net#9]
mavlinkgen --output=Ardupilotmega.cs ardupilotmega.xml
mavlinkgen --output=Pixhawk.cs pixhawk.xml

After generation both Ardupilotmega.cs, Pixhawk.cs, appear to be missing the UasMessage class that are inherited by 131 other classes such as UasHeartbeat: UasMessage{}... 

I know I am doing something wrong I just don't know what yet.  Thoughts?

**Comment by BTBlueSkies** [comment]
Hi dsuarezv/mavlink.,

I&#39;d like to add you to my professional network on LinkedIn.

- Karl

Accept: https://www.linkedin.com/blink?simpleRedirect=3gSczcMd3ATdjcTcP4PdP4SejkZh4BKrSBQonhFtCVF9C9NtkUStzB6fnBBiShBsC5EsOpQsSlRpRZBt6BSrCAZqSkConhzbmlQqnpKqiRQsSlRpORIrmkZpSVFqSdxsDgCpnhFtCV9pSlipn9Mfm4CujgJcTpMpzlWd6AJonpJsmdEbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5961731404847943680_500&markAsRead=


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=7AQbjdSs6oRuzhFbm5Srn5zq2QZp6BB9Bp9tnd7cPdTcAAJkjgNojAJiiR5mBlPj3xMkmV5kAlDsCpxe79PoQcJhzdMgPxpl49Fkjp9iS8Uh3hBclZTjQxxcBZ6jTlDll18r5hiqBEJgzlCqRlQe5gPh4pOcPtEpAFxpRtSoAMPs6sQkQVJr4tykSJikmJ3kClQqCdThAhRe50Tom9UjRdvhlZBomZormdNtCxirT5Frz1AhT9Fe4terjlkdQ5DgRcVol5mpANku79lgk51pR8MrlZasm5limJ7kk4Zp6BLr2pQsSlRpRZBt6BSrCAZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCujgJcTpMpzlWd6AJonpJsmdEbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5961731404847943680_500&amp;markAsRead=This email was intended for dsuarezv/mavlink. net. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoipQsSlRpRZBt6BSrCAZqSkCr79lpmdFtD9BkT9BrmZQsTlzfm4CujgJcTpMpzlWd6AJonpJsmdEbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5961731404847943680_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA
